### ISSUE TITLE
LocalBroadcastManager not found on android.support.v4

### ISSUE THREAD

**Issue by jonathangomz** [wonderpush/wonderpush-cordova-sdk#4]
When I open the project on Android Studio it cannot find the module on the WonderPushPlugin.java file like:
```java
import android.support.v4.content.LocalBroadcastManager
```

I have to use this other path:
```java
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
```

I don't know if this is a general problem or a specific one. Or even if it's a solution.

**Comment by ofavre** [comment]
We have migrated to AndroidX, thanks for reporting.
Closed by bbd66bf2d939ec71e99e34f25ea3e6d6886e2bb6.
